# Generated by Django 3.1.3 on 2020-11-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201125_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.FileField(default='Null', upload_to='img'),
            preserve_default=False,
        ),
    ]
